"""Added org and answer tables

Revision ID: d0832c7bd479
Revises: 40c8f7a0fd63
Create Date: 2016-04-24 09:28:45.419540

"""

# revision identifiers, used by Alembic.
revision = 'd0832c7bd479'
down_revision = '40c8f7a0fd63'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
